@startuml
left to right direction
:Cliente:
:Administrador:

Cliente --> (Iniciar sesion)
Cliente --> (Recuperar contraseña)
Cliente --> (Modificar contraseña)
Cliente --> (Cerrar sesion)

Administrador --> Cliente
Administrador --> (Registrar Usuario)
Administrador --> (Instalar programa)
@enduml