@startuml
left to right direction
:Cliente:

Cliente --> (Identificarse)
Cliente --> (Pagar)
Cliente --> (Eleir mensajero)
Cliente --> (Confirmar)

(Identificarse) .. (Registrarse) : <<Extend>>

(Pagar con transferencia) .. (Pagar)
(Pagar con tarjeta) .. (Pagar)
@enduml